source "https://rubygems.org"

gem "sinatra"
gem "sinatra-reloader"
gem "sinatra-activerecord"
gem "sqlite3"
gem "capistrano"
gem "capistrano-bundler"
gem "capistrano-passenger"
gem "capistrano-rbenv"
